### ISSUE TITLE
Investigate signed and unsigned integer usage in assembly blocks

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/solstat#12]
Using signed/regular opcodes for a signed and unsigned value can lead to unexpected behavior. There should be additional tests for these scenarios.

**Comment by 0xJepsen** [comment]
Can we close this in favor of more granular issue's that represent these bugs?

**Comment by Alexangelj** [comment]
Yes - but this is a granular issue since signed + unsigned integer use needs to be properly handled.

**Comment by clemlak** [comment]
It's a bit of a naive answer but after investigating the current code, I'd say that "it's fine" if we fuzz all the results + define precise bounds for the functions (inputs / outputs) and we compare the outputs to known results.

**Comment by clemlak** [comment]
https://github.com/primitivefinance/solstat/pull/28 covers it.
