### ISSUE TITLE
Output range failure

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/solstat#14]
Erfc output is in (0, 2) [FAIL]
  ```
x 57896044618658097711785492504343953926634992332820282019727792003956564819967
y 34272965671573232102
```
erfc returns a value that is not in the output domain

**Comment by Autoparallel** [comment]
I just tested:

`yarn cli --cdf 57896044618658097711785492504343953926634992332820282019727792003956564819967`

and received `1` as the output.

**Comment by Alexangelj** [comment]
We should have a better readme for the cli (its still heavily WIP) - it calls the javascript library which uses normal units!

**Comment by Autoparallel** [comment]
I was wondering about that.

**Comment by clemlak** [comment]
This bug is due to an overflow in the assembly part of the code, https://github.com/primitivefinance/solstat/commit/1f8c4f742d445bb90f09015cddd3cb9371916982 should cover it.
