### ISSUE TITLE
Erfc error around `x=0`

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/solstat#17]
Erfc max. error around symmetry point `(x=0)`:
```
  x 2685249746202
  y 999997000000952098
  min. err 2999999047902
```
Reporting minimum error under the assumption that `erfc(0) = 1` should hold
Problematic, because other functions `(ppf, getY)` make assumptions around the symmetry points and return hardcoded values

**Comment by Autoparallel** [comment]
Best I can see is that 
`yarn cli --cdf 0`
returns `0.5000000150000002`
which has an error of 1.5e-8

**Comment by clemlak** [comment]
https://github.com/primitivefinance/solstat/pull/28 fixed it.
