### ISSUE TITLE
Ierfc fails to catch infinities

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/solstat#18]
Ierfc should revert outside of input domain [FAIL]
```
  x 0
  y 100000000000000000000
```
Potentially problematic, because input `x=1` reverts (infinity), but `x<=0` returns `1`
```
  x 2000000000000000000
  y -100000000000000000000
```
Potentially problematic, because input `x=2e18 - 1` reverts (-infinity), but `x>=2e18` returns `-1`
Note: these values are hardcoded in ierfc

**Comment by clemlak** [comment]
https://github.com/primitivefinance/solstat/pull/28 fixes that!
