### ISSUE TITLE
Ierfc error on maximum bound. 

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/solstat#20]
Ierfc max. error found:
```
  x1 179
  y1 5822768677268435666
  x2 180
  y2 5822773609845769082
  min. err 4932577333416
```
Reporting minimum error under the assumption that `y2 < y1` should hold

**Comment by clemlak** [comment]
`ierfc()` was updated here https://github.com/primitivefinance/solstat/pull/28.
