### ISSUE TITLE
Mssing hardcoded outputs for conditional cases in Invariant.sol getX

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/solstat#24]
The Invariant.sol `getX` function computes the x reserves given y reserves. If the y reserves are zero, then the x reserves should be equal to 1, in solidity 1e18.

This must be hardcoded, because it's a mathematical property of the cdf and inverse cdf functions and it's not defined in solidity.

**Comment by MuradLev18** [comment]
This must be hardcoded, because it's a mathematical property of the cdf and inverse cdf functions and it's not defined in solidity.

**Comment by Alexangelj** [comment]
Fixed already, `main`.
